# -*- coding: utf-8 -*-
"""Autonomous Infrastructure Inspection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s21FxoN0mPFlvNrkv5VqUa3ZBCweY2TI
"""

!pip install -q ultralytics

from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow -q

from roboflow import Roboflow
rf = Roboflow(api_key="ROBOFLOW_API_KEY")

project = rf.workspace("yeeun-kim-fyvoj").project("pothole-vhmow")
version = project.version(18)
dataset = version.download("yolov8")

print("Dataset path:", dataset.location)

!pip install roboflow

from roboflow import Roboflow

rf = Roboflow(api_key="ROBOFLOW_API_KEY)

# ✅ Rust dataset (store in variable!)
rust = rf.workspace("zenil").project("rust-detection-4cr1b")
version_rust = rust.version(1)

dataset_rust = version_rust.download("yolov8")

# Save path
rust_path = dataset_rust.location
print("Rust dataset path:", rust_path)

from roboflow import Roboflow

rf = Roboflow(api_key="ROBOFLOW_API_KEY")

crack_project = rf.workspace("hamayls-workspace-yulm3").project("crack-fhmzv-smt1k")
crack_version = crack_project.version(1)

dataset_crack = crack_version.download("yolov8")

crack_path = dataset_crack.location
print("Crack dataset path:", crack_path)

import os
import shutil
import random
from pathlib import Path
import yaml
from collections import Counter

# ---------------------------
# --- Paths from datasets ---
# ---------------------------
photonet_path = dataset.location   # PhotoNet (pothole)
flagnets_path = rust_path          # FlagNet (rust)
crack_path = crack_path            # Crack dataset

# ---------------------------
# --- Final merged dataset ---
# ---------------------------
final_dataset_path = "/content/drive/MyDrive/DroneAI_Inspection"
os.makedirs(final_dataset_path, exist_ok=True)

# YOLOv8 folder structure
folders = ["images/train", "images/val", "images/test",
           "labels/train", "labels/val", "labels/test"]
for f in folders:
    os.makedirs(os.path.join(final_dataset_path, f), exist_ok=True)

# ---------------------------
# --- Helper function to copy & rename datasets ---
# ---------------------------
def copy_and_prefix(src_path, class_id, split_ratio=(0.8,0.1,0.1)):
    """
    Copies images and labels to merged dataset folder.
    Forces class IDs and adds a prefix for uniqueness.
    """
    img_dir = Path(src_path) / "train" / "images"
    lbl_dir = Path(src_path) / "train" / "labels"

    imgs = list(img_dir.glob("*.jpg")) + list(img_dir.glob("*.png"))
    random.shuffle(imgs)

    n = len(imgs)
    n_train = int(split_ratio[0]*n)
    n_val = int(split_ratio[1]*n)
    splits = {
        "train": imgs[:n_train],
        "val": imgs[n_train:n_train+n_val],
        "test": imgs[n_train+n_val:]
    }

    for split, files in splits.items():
        for img_file in files:
            lbl_file = lbl_dir / (img_file.stem + ".txt")

            # Add prefix for uniqueness
            new_name = f"{class_id}_{img_file.name}"

            # Copy image
            shutil.copy(img_file, os.path.join(final_dataset_path, f"images/{split}/{new_name}"))

            # Copy/modify label
            if lbl_file.exists():
                new_label_name = new_name.rsplit('.', 1)[0] + ".txt"
                new_label_path = os.path.join(final_dataset_path, f"labels/{split}/{new_label_name}")

                with open(lbl_file, "r") as f:
                    lines = f.readlines()

                new_lines = []
                for line in lines:
                    parts = line.strip().split()
                    parts[0] = str(class_id)  # force correct class
                    new_lines.append(" ".join(parts))

                with open(new_label_path, "w") as f:
                    f.write("\n".join(new_lines))

# ---------------------------
# --- Merge datasets ---
# ---------------------------
# pothole = 0
copy_and_prefix(photonet_path, class_id=0)

# rust = 1
copy_and_prefix(flagnets_path, class_id=1)

# crack = 2
copy_and_prefix(crack_path, class_id=2)

# ---------------------------
# --- Save YOLOv8 data.yaml ---
# ---------------------------
yaml_file_path = Path(final_dataset_path) / "data.yaml"
data_yaml = {
    "train": str(Path(final_dataset_path) / "images/train"),
    "val": str(Path(final_dataset_path) / "images/val"),
    "test": str(Path(final_dataset_path) / "images/test"),
    "names": ["pothole", "rust", "crack"],
    "nc": 3
}
with open(yaml_file_path, "w") as f:
    yaml.dump(data_yaml, f, sort_keys=False)
print(f"✅ YOLOv8 dataset YAML saved at: {yaml_file_path}")

# ---------------------------
# --- Dataset summary ---
# ---------------------------
splits = ["train", "val", "test"]
classes = {0: "pothole", 1: "rust", 2: "crack"}

total_images = 0
total_labels = 0
class_counter = Counter({c:0 for c in classes.values()})

for split in splits:
    img_dir = Path(final_dataset_path) / "images" / split
    lbl_dir = Path(final_dataset_path) / "labels" / split

    imgs = list(img_dir.glob("*.*"))
    total_images += len(imgs)

    lbl_files = list(lbl_dir.glob("*.txt"))
    total_labels += len(lbl_files)

    for lbl_file in lbl_files:
        with open(lbl_file, "r") as f:
            for line in f.readlines():
                if line.strip():
                    class_id = int(line.strip().split()[0])
                    class_counter[classes[class_id]] += 1

print("\n===== Dataset Summary =====")
print(f"Total images: {total_images}")
print(f"Total label files: {total_labels}")
print("Label count per class:")
for cls, count in class_counter.items():
    print(f" - {cls}: {count}")
print("===========================")

from ultralytics import YOLO

# Load previous best weights
model = YOLO("/content/drive/MyDrive/yolo_models/yolo_drone/best.pt")

# Train the model
model.train(
    data="/content/drive/MyDrive/DroneAI_Inspection/data.yaml",  # your merged dataset yaml
    epochs=40,               # high number, early stopping will handle stopping
    cls=1.5,
    imgsz=512,               # image size
    batch=8,                 # batch size
    project="/content/drive/MyDrive/yolo_models/yolo_drone",
    name="final_drone_model", # final model name
    pretrained=True,          # use previous weights
    augment=True,
    patience=10,              # early stopping patience
    save=True,                # save checkpoints (best + last by default)
    verbose=True
)

